#!/bin/bash

. /etc/.profile
#set -xv

: '
1. Purpose: To add new dbis or update dbi names
2. Description: run "asg_dbi_update".
3. Author: Anthony Davis
4. Date: 10/07/2025
5. Usage: asg_dbi_update
'

#------------------directorie paths
warpath="/usr/tmp/" # directory

#-------------------files generated by script below
tSfile="$HOST.site_dbshm.cf"                # deploy script generated file
logname="$warpath/"$USER".dbichanges.txt"   # deploy script generated file

#------------------Functions
# create a file if not existing
function makeAfile { if [ ! -f "$1" ]; then .dosu touch "$1"; .dosu chmod 777 "$1"; fi; }
# create a backup of a file
function makearev { .dosu cp "$1" "$1".$buExt; .dosu asgr "$1".$buExt; echo -e "Backup created: "$(ls -ltr $PWD/$1.$buExt); }

function chkd { chmod 777 "$1"; .dosu cp "$1" "$1".2; rm "$1"; .dosu mv "$1".2 "$1"; .dosu chmod 777 "$1"; }
# verify ownership is CIS and permissions are set to 777
function cchkd { if [ -n "$(ls -ltr "$1" | grep $USER)" ]; then chkd "$1"; else echo "$1 already owned by CIS"; fi; }

#------------------site_dbshm.cf updates staging
# Variables

makeAfile $logname
.dosu touch $logname
.dosu chmod 777 $logname

# Gather temp files
.dosu cp $CCSYSDIR/site_dbshm.cf $warpath/$tSfile
.dosu cp $CCSYSDIR/site_dbshm.cf $warpath/$tSfile.2
.dosu chmod 777 $warpath/$tSfile*

# If a line exists within the current site_dbshm.cf, remove from current file to not interfere with updated version
# Overwrite with temp version created through loop after each egrep -v to exclude dbis already in place in site_dbshm.cf
cut -d\" -f2 $warpath/$sourcefile | while IFS= read -r line; do
egrep -wv "^\"$line\"|^$line" $warpath/$tSfile > $warpath/$tSfile.2
.dosu cp $warpath/$tSfile.2 $warpath/$tSfile
done

# Set variable for last DBI in site_dbshm and append "r" to the line number to ensure the sourcefile is placed in the correct location
site_pre_var=$(echo $(grep -n -B2 "end of item" $warpath/$tSfile | grep -v \# | grep -v "end of item" | tail -1 | cut -d\- -f1)"r")

# Insert the current source list content to the updated site_dbshm file utlizing output from $site_pre_var
.dosu sed -i -e "$site_pre_var $warpath/$sourcefile" $warpath/$tSfile

#----------------------------------------------
# Activate the previously updated temporary site_dbshm.cf

echo "Activating modified site_dbshm.cf"

cd $CCSYSDIR/
if [ ! -f /usr/tmp//$tSfile ]; then
echo -e "Staged file not found. Review issues with script."
exit 1
fi

makearev site_dbshm.cf

adiff /usr/tmp//$tSfile site_dbshm.cf
.dosu cp /usr/tmp//$tSfile site_dbshm.cf
sleep 1
.dosu Rloaddbshm
.dosu CTImport -f site_dbshm.cf

break;;
#~~~~~ End update block

esac

done
